name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [master]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install wheel
        run: python -m pip install wheel==0.38.4 setuptools==65.5.1 setuptools_scm[toml]==7.0.5
      - name: Build distributions
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag
          SETUPTOOLS_SCM_DEBUG=1 python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
