name: Release
on:
  workflow_run:
    workflows: ["Test"]
    branches: [master]
    types:
      - completed

jobs:
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-python@v3
      - name: Install wheel
        run: python -m pip install wheel==0.38.4 setuptools==65.5.1
      # - name: Install cibuildwheel
      #   run: python -m pip install cibuildwheel==2.11.2
      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      # - name: Publish wheels to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     packages_dir: wheelhouse/
      - name: Build distributions
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
